ALTER TABLE messages
ADD COLUMN IF NOT EXISTS file TEXT,
ADD COLUMN IF NOT EXISTS file_name TEXT,
ADD COLUMN IF NOT EXISTS file_mime TEXT,
ADD COLUMN IF NOT EXISTS file_size BIGINT NOT NULL DEFAULT 0;
